spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_student
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  output:
    ansi:
      enabled: ALWAYS  # Options: ALWAYS, NEVER, DETECT
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,beans"
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%c){cyan} %clr(:){faint} %m%n"




